export const INTERVAL_FETCH_GLOBAL_STATS_WORKER=30000;
export const INTERVAL_ETH_NETWORK_WORKER=1000;
export const INTERVAL_ETH_ADDRESS_WORKER=1000;
export const INTERVAL_MEMBER_WORKER=1000;
export const INTERVAL_MARKET_WORKER=1000;
export const INTERVAL_POPULATION_WORKER=1000;

export const TIMEOUT_FLARE_DELETE=7000;
export const TIMEOUT_FLARE_DELETE_LONG=30000;

export const EVENT_DATA_ORIGIN_THRUBI="THRUBI";
export const EVENT_TYPE_MESSAGE="message";