export const INTERVAL_FETCH_GLOBAL_STATS_WORKER = 30000;
export const INTERVAL_ETH_NETWORK_WORKER = 1000;
export const INTERVAL_ETH_ADDRESS_WORKER = 1000;
export const INTERVAL_USER_WORKER = 1000;
export const INTERVAL_MEMBER_WORKER = 1000;
export const INTERVAL_MARKET_WORKER = 1000;
export const INTERVAL_POPULATION_WORKER = 1000;